from typing import Any

# Declare the LeapC Exception
class LeapCannotOpenDeviceError(Exception): ...

# Declare the Listener base class
class Listener:
    def __init__(self) -> None: ...
    # Add common LeapC callback events so your custom listener method overrides look clean
    def on_connection_event(self, event: Any) -> None: ...
    def on_device_event(self, event: Any) -> None: ...
    def on_tracking_event(self, event: Any) -> None: ...

# Your existing Connection object mapping
class Connection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def connect(self) -> None: ...
    def poll(self, timeout_ms: int = ...) -> Any: ...
    def add_listener(self, listener: Any) -> None: ...
    def open(self) -> Any: ...
    def set_tracking_mode(self, Any) -> Any: ...

class Device:
    id: int
    status: Any
    serial: str
    def open(self) -> Any: ...  # Allows "with event.device.open():" context mapping
    def get_info(self) -> Any: ...

class Event:
    device: Device
    type: Any
    timestamp: int

# Fallback catch-all for any missed LeapC bindings
def __getattr__(name: str) -> Any: ...